### ISSUE TITLE
404 on all routes

### ISSUE THREAD

**Issue by 28development** [Mindinventory/Golang-Project-Structure#2]
I set up the project and installed all dependencies. Further I setup a new database and added a new sample user to the table.
I am able to run 

`go run main.go`

The server start on `localhost:8099` if I visit the server on my browser I get a 404.
If I try to call this route in postman: `localhost:8099/api/v1/user-list`

I get this error

```
{
    "message": "Invalid request",
    "status": 1
}
```

**Comment by malvikiran** [comment]
@28development 

Can you please comment below the code from this path?
`Golang-Project-Structure-master/controllers/api/v1/user.go
`

   ```
 /* err := json.NewDecoder(c.Request.Body).Decode(&userService.User)
    if err != nil {
        u.Respond(c.Writer, u.Message(1, "Invalid request"))
        return
    } */
```

**Comment by 28development** [comment]
ok I commented that line, now I get following from postman v1:

```
{
    "data": {
        "id": 0,
        "name": "test",
        "email": "test@gmail.com"
    },
    "message": "This is from version 1 api",
    "status": 0
}
```

webapp still shows 404, what is the issue?

**Comment by malvikiran** [comment]
@28development send me your curl request.
