### ISSUE TITLE
[Question] With this design how are you returning statuscode from service?

### ISSUE THREAD

**Issue by mariofly** [Mindinventory/Golang-Project-Structure#3]
Hey Friends!

I have recently started a project using this structure and I was wondering how you recommend returning status codes from failures within a service? 

Thanks

**Comment by zubin7771** [comment]
@mariofly

1) For api success `status 0` is passed.
-  Check below parameters in the POST request for version2. Please try to removed one of the required field from the request like below screenshot.

![image](https://user-images.githubusercontent.com/63334467/108840427-5862a400-75fc-11eb-9d90-5f20798dfe36.png)


2) For api failure `status 1`.
- Check below parameters in the POST request for version2. Please try to removed one of the required field from the request like below screenshot.

![image](https://user-images.githubusercontent.com/63334467/108840662-b3949680-75fc-11eb-984f-a5953e6b8004.png)
