### ISSUE TITLE
Please update project structure to support go 1.18 workspace

### ISSUE THREAD

**Issue by 89t-yiming** [Mindinventory/Golang-Project-Structure#4]
Since workspace is released with go 1.18, the go project structure also need to change. 

Please update this repo, thank you!

**Comment by adityasinh-mi** [comment]
Hello @89trillion-ziqiang,
Thank you for bringing this to our attention! We have updated the repo to reflect the latest changes in the Go project structure and the updated workspace release. If you have any further questions or concerns, please don't hesitate to let us know. Thank you again for your feedback!

**Comment by rahulgauswami** [comment]
Closing this issue as it has been resolved.
